export default [
    {
        "_id": "A101",
        "title": "Propulsion Assignment",
        "course": "RS101",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-06",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-13",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-20",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A102",
        "title": "Combustion Analysis",
        "course": "RS101",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-13",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-20",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-27",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A103",
        "title": "Nozzle Design Project",
        "course": "RS101",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-20",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-27",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-06-03",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A201",
        "title": "Aerodynamics Quiz",
        "course": "RS102",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-06",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-13",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-20",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A202",
        "title": "Flow Analysis",
        "course": "RS102",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-13",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-20",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-27",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A203",
        "title": "Heating Analysis",
        "course": "RS102",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-20",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-27",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-06-03",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A301",
        "title": "Structural Design Task",
        "course": "RS103",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-06",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-13",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-20",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A302",
        "title": "Orbital Calculations",
        "course": "RS103",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-13",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-20",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-05-27",
        "availableUntilTime": "11:59 pm"
    },
    {
        "_id": "A303",
        "title": "Systems Engineering Exam",
        "course": "RS103",
        "description": "<p>The assignment is <span style='color:red;'>available online</span>.</p><p> Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com/' target='_blank'>Netlify</a>.</p><p> The landing page should include the following:</p><ul><li> Your full name and section,</li><li> Links to each of the lab assignments,</li><li> Link to the <strong>Kambaz</strong> application,</li><li> Links to all relevant source code repositories.</li></ul><p> The <strong>Kambaz</strong> application should include a link to navigate back to the landing page.</p>",
        "module": "Multiple Modules",
        "points": 100,
        "availableFromDate": "2024-05-06",
        "availableFromTime": "12:00 am",
        "dueDateDate": "2024-05-13",
        "dueDateTime": "11:59 pm",
        "availableUntilDate": "2024-06-03",
        "availableUntilTime": "11:59 pm"
    }
];