export default [
    {
        "_id": "Q101",
        "title": "Q1 - Propulsion Basics",
        "course": "RS101",
        "description": "Basic principles of rocket propulsion",
        "quizType": "Graded Quiz",
        "points": 29,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2023-09-21",
        "dueTime": "1:00 pm",
        "availableFromDate": "2023-09-14",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2023-09-21",
        "availableUntilTime": "1:00 pm",
        "published": true,
        "questionCount": 11
    },
    {
        "_id": "Q102",
        "title": "Q2 - Engine Types",
        "course": "RS101",
        "description": "Understanding different rocket engine types",
        "quizType": "Graded Quiz",
        "points": 32,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2023-10-05",
        "dueTime": "1:00 pm",
        "availableFromDate": "2023-09-28",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2023-10-05",
        "availableUntilTime": "1:00 pm",
        "published": true,
        "questionCount": 7
    },
    {
        "_id": "Q103",
        "title": "EXAM 1 - Propulsion Theory",
        "course": "RS101",
        "description": "Comprehensive exam on propulsion fundamentals",
        "quizType": "Graded Quiz",
        "points": 113,
        "assignmentGroup": "Exams",
        "shuffleAnswers": true,
        "timeLimit": 120,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "dueDate": "2023-10-28",
        "dueTime": "5:30 pm",
        "availableFromDate": "2023-10-28",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2023-10-28",
        "availableUntilTime": "5:30 pm",
        "published": true,
        "questionCount": 20
    },
    {
        "_id": "Q104",
        "title": "Q3 - Fuel Chemistry",
        "course": "RS101",
        "description": "Chemical properties of rocket fuels",
        "quizType": "Graded Quiz",
        "points": 38,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": true,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-10",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-12-03",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-15",
        "availableUntilTime": "11:59 pm",
        "published": true,
        "questionCount": 13
    },
    {
        "_id": "Q105",
        "title": "Q4 - Thrust Calculations",
        "course": "RS101",
        "description": "Mathematical analysis of thrust",
        "quizType": "Graded Quiz",
        "points": 31,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-20",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-12-13",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-20",
        "availableUntilTime": "11:59 pm",
        "published": false,
        "questionCount": 8
    },
    {
        "_id": "Q106",
        "title": "Q5 - Safety Protocols",
        "course": "RS101",
        "description": "Rocket testing and safety procedures",
        "quizType": "Graded Quiz",
        "points": 38,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-11-30",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-11-23",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-11-30",
        "availableUntilTime": "11:59 pm",
        "published": true,
        "questionCount": 10
    },
    {
        "_id": "Q107",
        "title": "EXAM 2 - Advanced Propulsion",
        "course": "RS101",
        "description": "Final comprehensive examination",
        "quizType": "Graded Quiz",
        "points": 104,
        "assignmentGroup": "Exams",
        "shuffleAnswers": true,
        "timeLimit": 120,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "dueDate": "2024-12-15",
        "dueTime": "10:30 am",
        "availableFromDate": "2024-12-15",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-15",
        "availableUntilTime": "1:00 pm",
        "published": true,
        "questionCount": 18
    },

    {
        "_id": "Q201",
        "title": "Q1 - Fluid Dynamics",
        "course": "RS102",
        "description": "Principles of fluid dynamics",
        "quizType": "Graded Quiz",
        "points": 25,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2023-09-25",
        "dueTime": "1:00 pm",
        "availableFromDate": "2023-09-18",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2023-09-25",
        "availableUntilTime": "1:00 pm",
        "published": true,
        "questionCount": 10
    },
    {
        "_id": "Q202",
        "title": "Q2 - Airfoil Design",
        "course": "RS102",
        "description": "Design principles of airfoils",
        "quizType": "Graded Quiz",
        "points": 30,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": true,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-08",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-12-01",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-08",
        "availableUntilTime": "11:59 pm",
        "published": true,
        "questionCount": 8
    },

    {
        "_id": "Q301",
        "title": "Q1 - Spacecraft Structures",
        "course": "RS103",
        "description": "Structural design of spacecraft",
        "quizType": "Graded Quiz",
        "points": 35,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-12",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-12-05",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-12",
        "availableUntilTime": "11:59 pm",
        "published": false,
        "questionCount": 12
    },

    {
        "_id": "Q701",
        "title": "Q1 - Elvish Basics",
        "course": "RS107",
        "description": "Introduction to Sindarin and Quenya",
        "quizType": "Graded Quiz",
        "points": 40,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 30,
        "multipleAttempts": true,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-18",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-12-11",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-18",
        "availableUntilTime": "11:59 pm",
        "published": true,
        "questionCount": 15
    },
    {
        "_id": "Q702",
        "title": "Q2 - Dwarvish Runes",
        "course": "RS107",
        "description": "Understanding Khuzdul script",
        "quizType": "Graded Quiz",
        "points": 28,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-12-05",
        "dueTime": "1:00 pm",
        "availableFromDate": "2024-11-28",
        "availableFromTime": "12:00 am",
        "availableUntilDate": "2024-12-05",
        "availableUntilTime": "11:59 pm",
        "published": true,
        "questionCount": 9
    }
];